# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.  # noqa: E501

    OpenAPI spec version: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fineract_client
from fineract_client.apis.roles_api import RolesApi  # noqa: E501
from fineract_client.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_actions_on_roles(self):
        """Test case for actions_on_roles

        Enable Role | Disable Role  # noqa: E501
        """
        pass

    def test_create_role(self):
        """Test case for create_role

        Create a New Role  # noqa: E501
        """
        pass

    def test_delete_role(self):
        """Test case for delete_role

        Delete a Role  # noqa: E501
        """
        pass

    def test_retrieve_all_roles(self):
        """Test case for retrieve_all_roles

        List Roles  # noqa: E501
        """
        pass

    def test_retrieve_role(self):
        """Test case for retrieve_role

        Retrieve a Role  # noqa: E501
        """
        pass

    def test_retrieve_role_permissions(self):
        """Test case for retrieve_role_permissions

        Retrieve a Role's Permissions  # noqa: E501
        """
        pass

    def test_update_role(self):
        """Test case for update_role

        Update a Role  # noqa: E501
        """
        pass

    def test_update_role_permissions(self):
        """Test case for update_role_permissions

        Update a Role's Permissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
