# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.  # noqa: E501

    OpenAPI spec version: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetLoansApprovalTemplateResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'approval_amount': 'float',
        'approval_date': 'date',
        'currency': 'GetLoanCurrency',
        'net_disbursal_amount': 'float'
    }

    attribute_map = {
        'approval_amount': 'approvalAmount',
        'approval_date': 'approvalDate',
        'currency': 'currency',
        'net_disbursal_amount': 'netDisbursalAmount'
    }

    def __init__(self, approval_amount=None, approval_date=None, currency=None, net_disbursal_amount=None):  # noqa: E501
        """GetLoansApprovalTemplateResponse - a model defined in Swagger"""  # noqa: E501
        self._approval_amount = None
        self._approval_date = None
        self._currency = None
        self._net_disbursal_amount = None
        self.discriminator = None
        if approval_amount is not None:
            self.approval_amount = approval_amount
        if approval_date is not None:
            self.approval_date = approval_date
        if currency is not None:
            self.currency = currency
        if net_disbursal_amount is not None:
            self.net_disbursal_amount = net_disbursal_amount

    @property
    def approval_amount(self):
        """Gets the approval_amount of this GetLoansApprovalTemplateResponse.  # noqa: E501


        :return: The approval_amount of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :rtype: float
        """
        return self._approval_amount

    @approval_amount.setter
    def approval_amount(self, approval_amount):
        """Sets the approval_amount of this GetLoansApprovalTemplateResponse.


        :param approval_amount: The approval_amount of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :type: float
        """

        self._approval_amount = approval_amount

    @property
    def approval_date(self):
        """Gets the approval_date of this GetLoansApprovalTemplateResponse.  # noqa: E501


        :return: The approval_date of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :rtype: date
        """
        return self._approval_date

    @approval_date.setter
    def approval_date(self, approval_date):
        """Sets the approval_date of this GetLoansApprovalTemplateResponse.


        :param approval_date: The approval_date of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :type: date
        """

        self._approval_date = approval_date

    @property
    def currency(self):
        """Gets the currency of this GetLoansApprovalTemplateResponse.  # noqa: E501


        :return: The currency of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :rtype: GetLoanCurrency
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this GetLoansApprovalTemplateResponse.


        :param currency: The currency of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :type: GetLoanCurrency
        """

        self._currency = currency

    @property
    def net_disbursal_amount(self):
        """Gets the net_disbursal_amount of this GetLoansApprovalTemplateResponse.  # noqa: E501


        :return: The net_disbursal_amount of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :rtype: float
        """
        return self._net_disbursal_amount

    @net_disbursal_amount.setter
    def net_disbursal_amount(self, net_disbursal_amount):
        """Sets the net_disbursal_amount of this GetLoansApprovalTemplateResponse.


        :param net_disbursal_amount: The net_disbursal_amount of this GetLoansApprovalTemplateResponse.  # noqa: E501
        :type: float
        """

        self._net_disbursal_amount = net_disbursal_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetLoansApprovalTemplateResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetLoansApprovalTemplateResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
