# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.  # noqa: E501

    OpenAPI spec version: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IsCatchUpRunningResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_catch_up_running': 'bool',
        'processing_date': 'date'
    }

    attribute_map = {
        'is_catch_up_running': 'isCatchUpRunning',
        'processing_date': 'processingDate'
    }

    def __init__(self, is_catch_up_running=None, processing_date=None):  # noqa: E501
        """IsCatchUpRunningResponse - a model defined in Swagger"""  # noqa: E501
        self._is_catch_up_running = None
        self._processing_date = None
        self.discriminator = None
        if is_catch_up_running is not None:
            self.is_catch_up_running = is_catch_up_running
        if processing_date is not None:
            self.processing_date = processing_date

    @property
    def is_catch_up_running(self):
        """Gets the is_catch_up_running of this IsCatchUpRunningResponse.  # noqa: E501


        :return: The is_catch_up_running of this IsCatchUpRunningResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_catch_up_running

    @is_catch_up_running.setter
    def is_catch_up_running(self, is_catch_up_running):
        """Sets the is_catch_up_running of this IsCatchUpRunningResponse.


        :param is_catch_up_running: The is_catch_up_running of this IsCatchUpRunningResponse.  # noqa: E501
        :type: bool
        """

        self._is_catch_up_running = is_catch_up_running

    @property
    def processing_date(self):
        """Gets the processing_date of this IsCatchUpRunningResponse.  # noqa: E501


        :return: The processing_date of this IsCatchUpRunningResponse.  # noqa: E501
        :rtype: date
        """
        return self._processing_date

    @processing_date.setter
    def processing_date(self, processing_date):
        """Sets the processing_date of this IsCatchUpRunningResponse.


        :param processing_date: The processing_date of this IsCatchUpRunningResponse.  # noqa: E501
        :type: date
        """

        self._processing_date = processing_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IsCatchUpRunningResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IsCatchUpRunningResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
