# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.  # noqa: E501

    OpenAPI spec version: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JournalEntryData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_number': 'str',
        'amount': 'float',
        'bank_number': 'str',
        'check_number': 'str',
        'comments': 'str',
        'created_by_user_id': 'int',
        'created_by_user_name': 'str',
        'created_date': 'date',
        'credits': 'list[CreditDebit]',
        'currency': 'CurrencyData',
        'currency_code': 'str',
        'date_format': 'str',
        'debits': 'list[CreditDebit]',
        'entity_id': 'int',
        'entity_type': 'EnumOptionData',
        'entry_type': 'EnumOptionData',
        'gl_account_code': 'str',
        'gl_account_id': 'int',
        'gl_account_name': 'str',
        'gl_account_type': 'EnumOptionData',
        'id': 'int',
        'locale': 'str',
        'manual_entry': 'bool',
        'office_id': 'int',
        'office_name': 'str',
        'office_running_balance': 'float',
        'organization_running_balance': 'float',
        'payment_type_id': 'int',
        'receipt_number': 'str',
        'reference_number': 'str',
        'reversed': 'bool',
        'routing_code': 'str',
        'row_index': 'int',
        'running_balance_computed': 'bool',
        'saving_transaction_id': 'int',
        'submitted_on_date': 'date',
        'transaction_date': 'date',
        'transaction_details': 'TransactionDetailData',
        'transaction_id': 'str'
    }

    attribute_map = {
        'account_number': 'accountNumber',
        'amount': 'amount',
        'bank_number': 'bankNumber',
        'check_number': 'checkNumber',
        'comments': 'comments',
        'created_by_user_id': 'createdByUserId',
        'created_by_user_name': 'createdByUserName',
        'created_date': 'createdDate',
        'credits': 'credits',
        'currency': 'currency',
        'currency_code': 'currencyCode',
        'date_format': 'dateFormat',
        'debits': 'debits',
        'entity_id': 'entityId',
        'entity_type': 'entityType',
        'entry_type': 'entryType',
        'gl_account_code': 'glAccountCode',
        'gl_account_id': 'glAccountId',
        'gl_account_name': 'glAccountName',
        'gl_account_type': 'glAccountType',
        'id': 'id',
        'locale': 'locale',
        'manual_entry': 'manualEntry',
        'office_id': 'officeId',
        'office_name': 'officeName',
        'office_running_balance': 'officeRunningBalance',
        'organization_running_balance': 'organizationRunningBalance',
        'payment_type_id': 'paymentTypeId',
        'receipt_number': 'receiptNumber',
        'reference_number': 'referenceNumber',
        'reversed': 'reversed',
        'routing_code': 'routingCode',
        'row_index': 'rowIndex',
        'running_balance_computed': 'runningBalanceComputed',
        'saving_transaction_id': 'savingTransactionId',
        'submitted_on_date': 'submittedOnDate',
        'transaction_date': 'transactionDate',
        'transaction_details': 'transactionDetails',
        'transaction_id': 'transactionId'
    }

    def __init__(self, account_number=None, amount=None, bank_number=None, check_number=None, comments=None, created_by_user_id=None, created_by_user_name=None, created_date=None, credits=None, currency=None, currency_code=None, date_format=None, debits=None, entity_id=None, entity_type=None, entry_type=None, gl_account_code=None, gl_account_id=None, gl_account_name=None, gl_account_type=None, id=None, locale=None, manual_entry=None, office_id=None, office_name=None, office_running_balance=None, organization_running_balance=None, payment_type_id=None, receipt_number=None, reference_number=None, reversed=None, routing_code=None, row_index=None, running_balance_computed=None, saving_transaction_id=None, submitted_on_date=None, transaction_date=None, transaction_details=None, transaction_id=None):  # noqa: E501
        """JournalEntryData - a model defined in Swagger"""  # noqa: E501
        self._account_number = None
        self._amount = None
        self._bank_number = None
        self._check_number = None
        self._comments = None
        self._created_by_user_id = None
        self._created_by_user_name = None
        self._created_date = None
        self._credits = None
        self._currency = None
        self._currency_code = None
        self._date_format = None
        self._debits = None
        self._entity_id = None
        self._entity_type = None
        self._entry_type = None
        self._gl_account_code = None
        self._gl_account_id = None
        self._gl_account_name = None
        self._gl_account_type = None
        self._id = None
        self._locale = None
        self._manual_entry = None
        self._office_id = None
        self._office_name = None
        self._office_running_balance = None
        self._organization_running_balance = None
        self._payment_type_id = None
        self._receipt_number = None
        self._reference_number = None
        self._reversed = None
        self._routing_code = None
        self._row_index = None
        self._running_balance_computed = None
        self._saving_transaction_id = None
        self._submitted_on_date = None
        self._transaction_date = None
        self._transaction_details = None
        self._transaction_id = None
        self.discriminator = None
        if account_number is not None:
            self.account_number = account_number
        if amount is not None:
            self.amount = amount
        if bank_number is not None:
            self.bank_number = bank_number
        if check_number is not None:
            self.check_number = check_number
        if comments is not None:
            self.comments = comments
        if created_by_user_id is not None:
            self.created_by_user_id = created_by_user_id
        if created_by_user_name is not None:
            self.created_by_user_name = created_by_user_name
        if created_date is not None:
            self.created_date = created_date
        if credits is not None:
            self.credits = credits
        if currency is not None:
            self.currency = currency
        if currency_code is not None:
            self.currency_code = currency_code
        if date_format is not None:
            self.date_format = date_format
        if debits is not None:
            self.debits = debits
        if entity_id is not None:
            self.entity_id = entity_id
        if entity_type is not None:
            self.entity_type = entity_type
        if entry_type is not None:
            self.entry_type = entry_type
        if gl_account_code is not None:
            self.gl_account_code = gl_account_code
        if gl_account_id is not None:
            self.gl_account_id = gl_account_id
        if gl_account_name is not None:
            self.gl_account_name = gl_account_name
        if gl_account_type is not None:
            self.gl_account_type = gl_account_type
        if id is not None:
            self.id = id
        if locale is not None:
            self.locale = locale
        if manual_entry is not None:
            self.manual_entry = manual_entry
        if office_id is not None:
            self.office_id = office_id
        if office_name is not None:
            self.office_name = office_name
        if office_running_balance is not None:
            self.office_running_balance = office_running_balance
        if organization_running_balance is not None:
            self.organization_running_balance = organization_running_balance
        if payment_type_id is not None:
            self.payment_type_id = payment_type_id
        if receipt_number is not None:
            self.receipt_number = receipt_number
        if reference_number is not None:
            self.reference_number = reference_number
        if reversed is not None:
            self.reversed = reversed
        if routing_code is not None:
            self.routing_code = routing_code
        if row_index is not None:
            self.row_index = row_index
        if running_balance_computed is not None:
            self.running_balance_computed = running_balance_computed
        if saving_transaction_id is not None:
            self.saving_transaction_id = saving_transaction_id
        if submitted_on_date is not None:
            self.submitted_on_date = submitted_on_date
        if transaction_date is not None:
            self.transaction_date = transaction_date
        if transaction_details is not None:
            self.transaction_details = transaction_details
        if transaction_id is not None:
            self.transaction_id = transaction_id

    @property
    def account_number(self):
        """Gets the account_number of this JournalEntryData.  # noqa: E501


        :return: The account_number of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number):
        """Sets the account_number of this JournalEntryData.


        :param account_number: The account_number of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._account_number = account_number

    @property
    def amount(self):
        """Gets the amount of this JournalEntryData.  # noqa: E501


        :return: The amount of this JournalEntryData.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this JournalEntryData.


        :param amount: The amount of this JournalEntryData.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def bank_number(self):
        """Gets the bank_number of this JournalEntryData.  # noqa: E501


        :return: The bank_number of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._bank_number

    @bank_number.setter
    def bank_number(self, bank_number):
        """Sets the bank_number of this JournalEntryData.


        :param bank_number: The bank_number of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._bank_number = bank_number

    @property
    def check_number(self):
        """Gets the check_number of this JournalEntryData.  # noqa: E501


        :return: The check_number of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._check_number

    @check_number.setter
    def check_number(self, check_number):
        """Sets the check_number of this JournalEntryData.


        :param check_number: The check_number of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._check_number = check_number

    @property
    def comments(self):
        """Gets the comments of this JournalEntryData.  # noqa: E501


        :return: The comments of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this JournalEntryData.


        :param comments: The comments of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def created_by_user_id(self):
        """Gets the created_by_user_id of this JournalEntryData.  # noqa: E501


        :return: The created_by_user_id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._created_by_user_id

    @created_by_user_id.setter
    def created_by_user_id(self, created_by_user_id):
        """Sets the created_by_user_id of this JournalEntryData.


        :param created_by_user_id: The created_by_user_id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._created_by_user_id = created_by_user_id

    @property
    def created_by_user_name(self):
        """Gets the created_by_user_name of this JournalEntryData.  # noqa: E501


        :return: The created_by_user_name of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._created_by_user_name

    @created_by_user_name.setter
    def created_by_user_name(self, created_by_user_name):
        """Sets the created_by_user_name of this JournalEntryData.


        :param created_by_user_name: The created_by_user_name of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._created_by_user_name = created_by_user_name

    @property
    def created_date(self):
        """Gets the created_date of this JournalEntryData.  # noqa: E501


        :return: The created_date of this JournalEntryData.  # noqa: E501
        :rtype: date
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this JournalEntryData.


        :param created_date: The created_date of this JournalEntryData.  # noqa: E501
        :type: date
        """

        self._created_date = created_date

    @property
    def credits(self):
        """Gets the credits of this JournalEntryData.  # noqa: E501


        :return: The credits of this JournalEntryData.  # noqa: E501
        :rtype: list[CreditDebit]
        """
        return self._credits

    @credits.setter
    def credits(self, credits):
        """Sets the credits of this JournalEntryData.


        :param credits: The credits of this JournalEntryData.  # noqa: E501
        :type: list[CreditDebit]
        """

        self._credits = credits

    @property
    def currency(self):
        """Gets the currency of this JournalEntryData.  # noqa: E501


        :return: The currency of this JournalEntryData.  # noqa: E501
        :rtype: CurrencyData
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this JournalEntryData.


        :param currency: The currency of this JournalEntryData.  # noqa: E501
        :type: CurrencyData
        """

        self._currency = currency

    @property
    def currency_code(self):
        """Gets the currency_code of this JournalEntryData.  # noqa: E501


        :return: The currency_code of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this JournalEntryData.


        :param currency_code: The currency_code of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._currency_code = currency_code

    @property
    def date_format(self):
        """Gets the date_format of this JournalEntryData.  # noqa: E501


        :return: The date_format of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._date_format

    @date_format.setter
    def date_format(self, date_format):
        """Sets the date_format of this JournalEntryData.


        :param date_format: The date_format of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._date_format = date_format

    @property
    def debits(self):
        """Gets the debits of this JournalEntryData.  # noqa: E501


        :return: The debits of this JournalEntryData.  # noqa: E501
        :rtype: list[CreditDebit]
        """
        return self._debits

    @debits.setter
    def debits(self, debits):
        """Sets the debits of this JournalEntryData.


        :param debits: The debits of this JournalEntryData.  # noqa: E501
        :type: list[CreditDebit]
        """

        self._debits = debits

    @property
    def entity_id(self):
        """Gets the entity_id of this JournalEntryData.  # noqa: E501


        :return: The entity_id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this JournalEntryData.


        :param entity_id: The entity_id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._entity_id = entity_id

    @property
    def entity_type(self):
        """Gets the entity_type of this JournalEntryData.  # noqa: E501


        :return: The entity_type of this JournalEntryData.  # noqa: E501
        :rtype: EnumOptionData
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this JournalEntryData.


        :param entity_type: The entity_type of this JournalEntryData.  # noqa: E501
        :type: EnumOptionData
        """

        self._entity_type = entity_type

    @property
    def entry_type(self):
        """Gets the entry_type of this JournalEntryData.  # noqa: E501


        :return: The entry_type of this JournalEntryData.  # noqa: E501
        :rtype: EnumOptionData
        """
        return self._entry_type

    @entry_type.setter
    def entry_type(self, entry_type):
        """Sets the entry_type of this JournalEntryData.


        :param entry_type: The entry_type of this JournalEntryData.  # noqa: E501
        :type: EnumOptionData
        """

        self._entry_type = entry_type

    @property
    def gl_account_code(self):
        """Gets the gl_account_code of this JournalEntryData.  # noqa: E501


        :return: The gl_account_code of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._gl_account_code

    @gl_account_code.setter
    def gl_account_code(self, gl_account_code):
        """Sets the gl_account_code of this JournalEntryData.


        :param gl_account_code: The gl_account_code of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._gl_account_code = gl_account_code

    @property
    def gl_account_id(self):
        """Gets the gl_account_id of this JournalEntryData.  # noqa: E501


        :return: The gl_account_id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._gl_account_id

    @gl_account_id.setter
    def gl_account_id(self, gl_account_id):
        """Sets the gl_account_id of this JournalEntryData.


        :param gl_account_id: The gl_account_id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._gl_account_id = gl_account_id

    @property
    def gl_account_name(self):
        """Gets the gl_account_name of this JournalEntryData.  # noqa: E501


        :return: The gl_account_name of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._gl_account_name

    @gl_account_name.setter
    def gl_account_name(self, gl_account_name):
        """Sets the gl_account_name of this JournalEntryData.


        :param gl_account_name: The gl_account_name of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._gl_account_name = gl_account_name

    @property
    def gl_account_type(self):
        """Gets the gl_account_type of this JournalEntryData.  # noqa: E501


        :return: The gl_account_type of this JournalEntryData.  # noqa: E501
        :rtype: EnumOptionData
        """
        return self._gl_account_type

    @gl_account_type.setter
    def gl_account_type(self, gl_account_type):
        """Sets the gl_account_type of this JournalEntryData.


        :param gl_account_type: The gl_account_type of this JournalEntryData.  # noqa: E501
        :type: EnumOptionData
        """

        self._gl_account_type = gl_account_type

    @property
    def id(self):
        """Gets the id of this JournalEntryData.  # noqa: E501


        :return: The id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JournalEntryData.


        :param id: The id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def locale(self):
        """Gets the locale of this JournalEntryData.  # noqa: E501


        :return: The locale of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this JournalEntryData.


        :param locale: The locale of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def manual_entry(self):
        """Gets the manual_entry of this JournalEntryData.  # noqa: E501


        :return: The manual_entry of this JournalEntryData.  # noqa: E501
        :rtype: bool
        """
        return self._manual_entry

    @manual_entry.setter
    def manual_entry(self, manual_entry):
        """Sets the manual_entry of this JournalEntryData.


        :param manual_entry: The manual_entry of this JournalEntryData.  # noqa: E501
        :type: bool
        """

        self._manual_entry = manual_entry

    @property
    def office_id(self):
        """Gets the office_id of this JournalEntryData.  # noqa: E501


        :return: The office_id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._office_id

    @office_id.setter
    def office_id(self, office_id):
        """Sets the office_id of this JournalEntryData.


        :param office_id: The office_id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._office_id = office_id

    @property
    def office_name(self):
        """Gets the office_name of this JournalEntryData.  # noqa: E501


        :return: The office_name of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._office_name

    @office_name.setter
    def office_name(self, office_name):
        """Sets the office_name of this JournalEntryData.


        :param office_name: The office_name of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._office_name = office_name

    @property
    def office_running_balance(self):
        """Gets the office_running_balance of this JournalEntryData.  # noqa: E501


        :return: The office_running_balance of this JournalEntryData.  # noqa: E501
        :rtype: float
        """
        return self._office_running_balance

    @office_running_balance.setter
    def office_running_balance(self, office_running_balance):
        """Sets the office_running_balance of this JournalEntryData.


        :param office_running_balance: The office_running_balance of this JournalEntryData.  # noqa: E501
        :type: float
        """

        self._office_running_balance = office_running_balance

    @property
    def organization_running_balance(self):
        """Gets the organization_running_balance of this JournalEntryData.  # noqa: E501


        :return: The organization_running_balance of this JournalEntryData.  # noqa: E501
        :rtype: float
        """
        return self._organization_running_balance

    @organization_running_balance.setter
    def organization_running_balance(self, organization_running_balance):
        """Sets the organization_running_balance of this JournalEntryData.


        :param organization_running_balance: The organization_running_balance of this JournalEntryData.  # noqa: E501
        :type: float
        """

        self._organization_running_balance = organization_running_balance

    @property
    def payment_type_id(self):
        """Gets the payment_type_id of this JournalEntryData.  # noqa: E501


        :return: The payment_type_id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._payment_type_id

    @payment_type_id.setter
    def payment_type_id(self, payment_type_id):
        """Sets the payment_type_id of this JournalEntryData.


        :param payment_type_id: The payment_type_id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._payment_type_id = payment_type_id

    @property
    def receipt_number(self):
        """Gets the receipt_number of this JournalEntryData.  # noqa: E501


        :return: The receipt_number of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._receipt_number

    @receipt_number.setter
    def receipt_number(self, receipt_number):
        """Sets the receipt_number of this JournalEntryData.


        :param receipt_number: The receipt_number of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._receipt_number = receipt_number

    @property
    def reference_number(self):
        """Gets the reference_number of this JournalEntryData.  # noqa: E501


        :return: The reference_number of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """Sets the reference_number of this JournalEntryData.


        :param reference_number: The reference_number of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._reference_number = reference_number

    @property
    def reversed(self):
        """Gets the reversed of this JournalEntryData.  # noqa: E501


        :return: The reversed of this JournalEntryData.  # noqa: E501
        :rtype: bool
        """
        return self._reversed

    @reversed.setter
    def reversed(self, reversed):
        """Sets the reversed of this JournalEntryData.


        :param reversed: The reversed of this JournalEntryData.  # noqa: E501
        :type: bool
        """

        self._reversed = reversed

    @property
    def routing_code(self):
        """Gets the routing_code of this JournalEntryData.  # noqa: E501


        :return: The routing_code of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._routing_code

    @routing_code.setter
    def routing_code(self, routing_code):
        """Sets the routing_code of this JournalEntryData.


        :param routing_code: The routing_code of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._routing_code = routing_code

    @property
    def row_index(self):
        """Gets the row_index of this JournalEntryData.  # noqa: E501


        :return: The row_index of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._row_index

    @row_index.setter
    def row_index(self, row_index):
        """Sets the row_index of this JournalEntryData.


        :param row_index: The row_index of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._row_index = row_index

    @property
    def running_balance_computed(self):
        """Gets the running_balance_computed of this JournalEntryData.  # noqa: E501


        :return: The running_balance_computed of this JournalEntryData.  # noqa: E501
        :rtype: bool
        """
        return self._running_balance_computed

    @running_balance_computed.setter
    def running_balance_computed(self, running_balance_computed):
        """Sets the running_balance_computed of this JournalEntryData.


        :param running_balance_computed: The running_balance_computed of this JournalEntryData.  # noqa: E501
        :type: bool
        """

        self._running_balance_computed = running_balance_computed

    @property
    def saving_transaction_id(self):
        """Gets the saving_transaction_id of this JournalEntryData.  # noqa: E501


        :return: The saving_transaction_id of this JournalEntryData.  # noqa: E501
        :rtype: int
        """
        return self._saving_transaction_id

    @saving_transaction_id.setter
    def saving_transaction_id(self, saving_transaction_id):
        """Sets the saving_transaction_id of this JournalEntryData.


        :param saving_transaction_id: The saving_transaction_id of this JournalEntryData.  # noqa: E501
        :type: int
        """

        self._saving_transaction_id = saving_transaction_id

    @property
    def submitted_on_date(self):
        """Gets the submitted_on_date of this JournalEntryData.  # noqa: E501


        :return: The submitted_on_date of this JournalEntryData.  # noqa: E501
        :rtype: date
        """
        return self._submitted_on_date

    @submitted_on_date.setter
    def submitted_on_date(self, submitted_on_date):
        """Sets the submitted_on_date of this JournalEntryData.


        :param submitted_on_date: The submitted_on_date of this JournalEntryData.  # noqa: E501
        :type: date
        """

        self._submitted_on_date = submitted_on_date

    @property
    def transaction_date(self):
        """Gets the transaction_date of this JournalEntryData.  # noqa: E501


        :return: The transaction_date of this JournalEntryData.  # noqa: E501
        :rtype: date
        """
        return self._transaction_date

    @transaction_date.setter
    def transaction_date(self, transaction_date):
        """Sets the transaction_date of this JournalEntryData.


        :param transaction_date: The transaction_date of this JournalEntryData.  # noqa: E501
        :type: date
        """

        self._transaction_date = transaction_date

    @property
    def transaction_details(self):
        """Gets the transaction_details of this JournalEntryData.  # noqa: E501


        :return: The transaction_details of this JournalEntryData.  # noqa: E501
        :rtype: TransactionDetailData
        """
        return self._transaction_details

    @transaction_details.setter
    def transaction_details(self, transaction_details):
        """Sets the transaction_details of this JournalEntryData.


        :param transaction_details: The transaction_details of this JournalEntryData.  # noqa: E501
        :type: TransactionDetailData
        """

        self._transaction_details = transaction_details

    @property
    def transaction_id(self):
        """Gets the transaction_id of this JournalEntryData.  # noqa: E501


        :return: The transaction_id of this JournalEntryData.  # noqa: E501
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this JournalEntryData.


        :param transaction_id: The transaction_id of this JournalEntryData.  # noqa: E501
        :type: str
        """

        self._transaction_id = transaction_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JournalEntryData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JournalEntryData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
