# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.

    The version of the OpenAPI document: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fineract_client.models.get_clients_client_id_accounts_response import GetClientsClientIdAccountsResponse

class TestGetClientsClientIdAccountsResponse(unittest.TestCase):
    """GetClientsClientIdAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClientsClientIdAccountsResponse:
        """Test GetClientsClientIdAccountsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClientsClientIdAccountsResponse`
        """
        model = GetClientsClientIdAccountsResponse()
        if include_optional:
            return GetClientsClientIdAccountsResponse(
                loan_accounts = [
                    fineract_client.models.get_clients_loan_accounts.GetClientsLoanAccounts(
                        account_no = '000000001', 
                        currency = fineract_client.models.get_clients_loans_accounts_currency.GetClientsLoansAccountsCurrency(
                            code = 'USD', 
                            decimal_places = 2, 
                            display_label = 'US Dollar ($)', 
                            display_symbol = '$', 
                            name = 'US Dollar', 
                            name_code = 'currency.USD', ), 
                        external_id = '456', 
                        id = 1, 
                        loan_cycle = 1, 
                        loan_type = fineract_client.models.get_clients_loan_accounts_type.GetClientsLoanAccountsType(
                            code = 'loanType.individual', 
                            description = 'Individual', 
                            id = 1, ), 
                        product_id = 1, 
                        product_name = 'TestOne', 
                        short_product_name = 'OP', 
                        status = fineract_client.models.get_clients_loan_accounts_status.GetClientsLoanAccountsStatus(
                            active = True, 
                            closed = False, 
                            closed_obligations_met = False, 
                            closed_rescheduled = False, 
                            closed_written_off = False, 
                            code = 'loanStatusType.active', 
                            description = 'Active', 
                            id = 300, 
                            overpaid = False, 
                            pending_approval = False, 
                            waiting_for_disbursal = False, ), )
                    ],
                savings_accounts = [
                    fineract_client.models.get_clients_savings_accounts.GetClientsSavingsAccounts(
                        account_no = '000000007', 
                        currency = fineract_client.models.get_clients_savings_accounts_currency.GetClientsSavingsAccountsCurrency(
                            code = 'USD', 
                            decimal_places = 2, 
                            display_label = 'US Dollar ($)', 
                            display_symbol = '$', 
                            name = 'US Dollar', 
                            name_code = 'currency.USD', ), 
                        deposit_type = fineract_client.models.get_clients_savings_accounts_deposit_type.GetClientsSavingsAccountsDepositType(
                            code = 'depositAccountType.savingsDeposit', 
                            id = 100, 
                            value = 'Savings', ), 
                        id = 7, 
                        product_id = 2, 
                        product_name = 'Other product', 
                        short_product_name = 'OP', 
                        status = fineract_client.models.get_clients_savings_accounts_status.GetClientsSavingsAccountsStatus(
                            active = False, 
                            approved = False, 
                            closed = False, 
                            code = 'savingsAccountStatusType.submitted.and.pending.approval', 
                            id = 100, 
                            matured = False, 
                            premature_closed = False, 
                            rejected = False, 
                            submitted_and_pending_approval = True, 
                            transfer_in_progress = False, 
                            transfer_on_hold = False, 
                            value = 'Submitted and pending approval', 
                            withdrawn_by_applicant = False, ), )
                    ]
            )
        else:
            return GetClientsClientIdAccountsResponse(
        )
        """

    def testGetClientsClientIdAccountsResponse(self):
        """Test GetClientsClientIdAccountsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
