# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.

    The version of the OpenAPI document: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fineract_client.models.get_self_savings_accounts_account_id_transactions_transaction_id_response import GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse

class TestGetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse(unittest.TestCase):
    """GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse:
        """Test GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse`
        """
        model = GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse()
        if include_optional:
            return GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse(
                account_id = 1,
                account_no = 1,
                amount = 5000,
                currency = fineract_client.models.get_self_savings_transaction_currency.GetSelfSavingsTransactionCurrency(
                    code = 'USD', 
                    decimal_places = 2, 
                    display_label = 'US Dollar ($)', 
                    display_symbol = '$', 
                    in_multiples_of = 0, 
                    name = 'US Dollar', 
                    name_code = 'currency.USD', ),
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                id = 1,
                payment_detail_data = fineract_client.models.get_self_savings_payment_detail_data.GetSelfSavingsPaymentDetailData(
                    account_number = 56, 
                    bank_number = 56, 
                    check_number = 56, 
                    id = 62, 
                    payment_type = fineract_client.models.get_self_savings_payment_type.GetSelfSavingsPaymentType(
                        id = 11, 
                        name = 'cash', ), 
                    receipt_number = 56, 
                    routing_code = 56, ),
                reversed = True,
                running_balance = 0,
                transaction_type = fineract_client.models.get_self_savings_transaction_type.GetSelfSavingsTransactionType(
                    code = 'savingsAccountTransactionType.withdrawal', 
                    deposit = False, 
                    description = 'Withdrawal', 
                    fee_deduction = False, 
                    id = 2, 
                    interest_posting = False, 
                    withdrawal = True, )
            )
        else:
            return GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse(
        )
        """

    def testGetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse(self):
        """Test GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
