# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.

    The version of the OpenAPI document: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fineract_client.api.inter_operation_api import InterOperationApi


class TestInterOperationApi(unittest.TestCase):
    """InterOperationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InterOperationApi()

    def tearDown(self) -> None:
        pass

    def test_create_quote(self) -> None:
        """Test case for create_quote

        Calculate Interoperation Quote
        """
        pass

    def test_create_transaction_request(self) -> None:
        """Test case for create_transaction_request

        Allow Interoperation Transaction Request
        """
        pass

    def test_delete_account_identifier(self) -> None:
        """Test case for delete_account_identifier

        Allow Interoperation Identifier registration
        """
        pass

    def test_delete_account_identifier1(self) -> None:
        """Test case for delete_account_identifier1

        Allow Interoperation Identifier registration
        """
        pass

    def test_disburse_loan(self) -> None:
        """Test case for disburse_loan

        Disburse Loan by Account Id
        """
        pass

    def test_get_account_by_identifier(self) -> None:
        """Test case for get_account_by_identifier

        Query Interoperation Account by secondary identifier
        """
        pass

    def test_get_account_by_identifier1(self) -> None:
        """Test case for get_account_by_identifier1

        Query Interoperation Account by secondary identifier
        """
        pass

    def test_get_account_details(self) -> None:
        """Test case for get_account_details

        Query Interoperation Account details
        """
        pass

    def test_get_account_identifiers(self) -> None:
        """Test case for get_account_identifiers

        Query Interoperation secondary identifiers by Account Id
        """
        pass

    def test_get_account_transactions(self) -> None:
        """Test case for get_account_transactions

        Query transactions by Account Id
        """
        pass

    def test_get_client_kyc(self) -> None:
        """Test case for get_client_kyc

        Query KYC by Account Id
        """
        pass

    def test_get_quote(self) -> None:
        """Test case for get_quote

        Query Interoperation Quote
        """
        pass

    def test_get_transaction_request(self) -> None:
        """Test case for get_transaction_request

        Query Interoperation Transaction Request
        """
        pass

    def test_get_transfer(self) -> None:
        """Test case for get_transfer

        Query Interoperation Transfer
        """
        pass

    def test_health(self) -> None:
        """Test case for health

        Query Interoperation Health Request
        """
        pass

    def test_loan_repayment(self) -> None:
        """Test case for loan_repayment

        Disburse Loan by Account Id
        """
        pass

    def test_perform_transfer(self) -> None:
        """Test case for perform_transfer

        Prepare Interoperation Transfer
        """
        pass

    def test_register_account_identifier(self) -> None:
        """Test case for register_account_identifier

        Interoperation Identifier registration
        """
        pass

    def test_register_account_identifier1(self) -> None:
        """Test case for register_account_identifier1

        Interoperation Identifier registration
        """
        pass


if __name__ == '__main__':
    unittest.main()
