# coding: utf-8

"""
    Apache Fineract REST API

    Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.

    The version of the OpenAPI document: 1.11.0-SNAPSHOT
    Contact: dev@fineract.apache.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from fineract_client.models.get_client_id_product_id_accounting_mappings import GetClientIdProductIdAccountingMappings
from fineract_client.models.get_client_id_product_id_lockin_period_frequency_type_options import GetClientIdProductIdLockinPeriodFrequencyTypeOptions
from fineract_client.models.get_client_id_product_id_minimum_active_period_frequency_type_options import GetClientIdProductIdMinimumActivePeriodFrequencyTypeOptions
from fineract_client.models.get_share_accounts_charge_options import GetShareAccountsChargeOptions
from fineract_client.models.get_share_accounts_client_id_product_id_accounting_rule import GetShareAccountsClientIdProductIdAccountingRule
from fineract_client.models.get_share_accounts_client_id_product_id_lock_period_type_enum import GetShareAccountsClientIdProductIdLockPeriodTypeEnum
from fineract_client.models.get_share_accounts_client_id_product_id_minimum_active_period_for_dividends_type_enum import GetShareAccountsClientIdProductIdMinimumActivePeriodForDividendsTypeEnum
from fineract_client.models.get_share_accounts_currency import GetShareAccountsCurrency
from typing import Optional, Set
from typing_extensions import Self

class GetClientIdProductIdProductOptions(BaseModel):
    """
    GetClientIdProductIdProductOptions
    """ # noqa: E501
    accounting_mapping_options: Optional[Dict[str, Any]] = Field(default=None, alias="accountingMappingOptions")
    accounting_mappings: Optional[GetClientIdProductIdAccountingMappings] = Field(default=None, alias="accountingMappings")
    accounting_rule: Optional[GetShareAccountsClientIdProductIdAccountingRule] = Field(default=None, alias="accountingRule")
    allow_dividend_calculation_for_inactive_clients: Optional[StrictBool] = Field(default=None, alias="allowDividendCalculationForInactiveClients")
    charge_options: Optional[GetShareAccountsChargeOptions] = Field(default=None, alias="chargeOptions")
    charges: Optional[StrictStr] = None
    currency: Optional[GetShareAccountsCurrency] = None
    currency_options: Optional[GetShareAccountsCurrency] = Field(default=None, alias="currencyOptions")
    description: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    lockin_period: Optional[StrictInt] = Field(default=None, alias="lockinPeriod")
    lockin_period_enum: Optional[GetShareAccountsClientIdProductIdLockPeriodTypeEnum] = Field(default=None, alias="lockinPeriodEnum")
    lockin_period_frequency_type_options: Optional[GetClientIdProductIdLockinPeriodFrequencyTypeOptions] = Field(default=None, alias="lockinPeriodFrequencyTypeOptions")
    market_price: Optional[StrictStr] = Field(default=None, alias="marketPrice")
    maximum_shares: Optional[StrictInt] = Field(default=None, alias="maximumShares")
    minimum_active_period: Optional[StrictInt] = Field(default=None, alias="minimumActivePeriod")
    minimum_active_period_for_dividends_type_enum: Optional[GetShareAccountsClientIdProductIdMinimumActivePeriodForDividendsTypeEnum] = Field(default=None, alias="minimumActivePeriodForDividendsTypeEnum")
    minimum_active_period_frequency_type_options: Optional[GetClientIdProductIdMinimumActivePeriodFrequencyTypeOptions] = Field(default=None, alias="minimumActivePeriodFrequencyTypeOptions")
    minimum_shares: Optional[StrictInt] = Field(default=None, alias="minimumShares")
    name: Optional[StrictStr] = None
    norminal_shares: Optional[StrictInt] = Field(default=None, alias="norminalShares")
    share_capital: Optional[StrictInt] = Field(default=None, alias="shareCapital")
    short_name: Optional[StrictStr] = Field(default=None, alias="shortName")
    total_shares: Optional[StrictInt] = Field(default=None, alias="totalShares")
    total_shares_issued: Optional[StrictInt] = Field(default=None, alias="totalSharesIssued")
    unit_price: Optional[StrictInt] = Field(default=None, alias="unitPrice")
    __properties: ClassVar[List[str]] = ["accountingMappingOptions", "accountingMappings", "accountingRule", "allowDividendCalculationForInactiveClients", "chargeOptions", "charges", "currency", "currencyOptions", "description", "id", "lockinPeriod", "lockinPeriodEnum", "lockinPeriodFrequencyTypeOptions", "marketPrice", "maximumShares", "minimumActivePeriod", "minimumActivePeriodForDividendsTypeEnum", "minimumActivePeriodFrequencyTypeOptions", "minimumShares", "name", "norminalShares", "shareCapital", "shortName", "totalShares", "totalSharesIssued", "unitPrice"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetClientIdProductIdProductOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of accounting_mappings
        if self.accounting_mappings:
            _dict['accountingMappings'] = self.accounting_mappings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of accounting_rule
        if self.accounting_rule:
            _dict['accountingRule'] = self.accounting_rule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of charge_options
        if self.charge_options:
            _dict['chargeOptions'] = self.charge_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of currency_options
        if self.currency_options:
            _dict['currencyOptions'] = self.currency_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lockin_period_enum
        if self.lockin_period_enum:
            _dict['lockinPeriodEnum'] = self.lockin_period_enum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lockin_period_frequency_type_options
        if self.lockin_period_frequency_type_options:
            _dict['lockinPeriodFrequencyTypeOptions'] = self.lockin_period_frequency_type_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of minimum_active_period_for_dividends_type_enum
        if self.minimum_active_period_for_dividends_type_enum:
            _dict['minimumActivePeriodForDividendsTypeEnum'] = self.minimum_active_period_for_dividends_type_enum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of minimum_active_period_frequency_type_options
        if self.minimum_active_period_frequency_type_options:
            _dict['minimumActivePeriodFrequencyTypeOptions'] = self.minimum_active_period_frequency_type_options.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetClientIdProductIdProductOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountingMappingOptions": obj.get("accountingMappingOptions"),
            "accountingMappings": GetClientIdProductIdAccountingMappings.from_dict(obj["accountingMappings"]) if obj.get("accountingMappings") is not None else None,
            "accountingRule": GetShareAccountsClientIdProductIdAccountingRule.from_dict(obj["accountingRule"]) if obj.get("accountingRule") is not None else None,
            "allowDividendCalculationForInactiveClients": obj.get("allowDividendCalculationForInactiveClients"),
            "chargeOptions": GetShareAccountsChargeOptions.from_dict(obj["chargeOptions"]) if obj.get("chargeOptions") is not None else None,
            "charges": obj.get("charges"),
            "currency": GetShareAccountsCurrency.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "currencyOptions": GetShareAccountsCurrency.from_dict(obj["currencyOptions"]) if obj.get("currencyOptions") is not None else None,
            "description": obj.get("description"),
            "id": obj.get("id"),
            "lockinPeriod": obj.get("lockinPeriod"),
            "lockinPeriodEnum": GetShareAccountsClientIdProductIdLockPeriodTypeEnum.from_dict(obj["lockinPeriodEnum"]) if obj.get("lockinPeriodEnum") is not None else None,
            "lockinPeriodFrequencyTypeOptions": GetClientIdProductIdLockinPeriodFrequencyTypeOptions.from_dict(obj["lockinPeriodFrequencyTypeOptions"]) if obj.get("lockinPeriodFrequencyTypeOptions") is not None else None,
            "marketPrice": obj.get("marketPrice"),
            "maximumShares": obj.get("maximumShares"),
            "minimumActivePeriod": obj.get("minimumActivePeriod"),
            "minimumActivePeriodForDividendsTypeEnum": GetShareAccountsClientIdProductIdMinimumActivePeriodForDividendsTypeEnum.from_dict(obj["minimumActivePeriodForDividendsTypeEnum"]) if obj.get("minimumActivePeriodForDividendsTypeEnum") is not None else None,
            "minimumActivePeriodFrequencyTypeOptions": GetClientIdProductIdMinimumActivePeriodFrequencyTypeOptions.from_dict(obj["minimumActivePeriodFrequencyTypeOptions"]) if obj.get("minimumActivePeriodFrequencyTypeOptions") is not None else None,
            "minimumShares": obj.get("minimumShares"),
            "name": obj.get("name"),
            "norminalShares": obj.get("norminalShares"),
            "shareCapital": obj.get("shareCapital"),
            "shortName": obj.get("shortName"),
            "totalShares": obj.get("totalShares"),
            "totalSharesIssued": obj.get("totalSharesIssued"),
            "unitPrice": obj.get("unitPrice")
        })
        return _obj


